[versions]

catFactClient = "0.2.0"
coroutines = "1.10.1"
honeycomb = "1.7.0"
jacoco = "0.8.7"
jooq = "0.9.15"
jooq_docker_plugin = "0.3.9"
jvmTarget = "17"
kotlin = "2.1.0"
mockk = "1.13.16"
mockkSpring = "4.0.2"
postgres = "42.7.4"
pwd = "6.42.0"
spotless = "6.25.0"
spring_dependency_management = "1.1.0"
springboot = "3.1.0"
springdoc = "2.8.4"
swagger = "6.6.0"
testcontainers = "1.20.4"

[libraries]

# Cat Fact Client

cat_fact_client = { module = "com.yonatankarp:cat-fact-client", version.ref = "catFactClient" }

# Kotlin & Coroutines
kotlin_core = { module = "org.jetbrains.kotlin:kotlin-stdlib" }
kotlin_jackson_module = { module = "com.fasterxml.jackson.module:jackson-module-kotlin" }
kotlin_reflection = { module = "org.jetbrains.kotlin:kotlin-reflect" }
kotlinx_coroutines_core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx_coroutines_reactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor", version.ref = "coroutines" }
kotlinx_coroutines_test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

# Spring Boot
springboot_actuator_starter = { module = "org.springframework.boot:spring-boot-starter-actuator" }
springboot_jdbc_starter = { module = "org.springframework.boot:spring-boot-starter-jdbc" }
springboot_jooq_starter = { module = "org.springframework.boot:spring-boot-starter-jooq" }
springboot_test_starter = { module = "org.springframework.boot:spring-boot-starter-test" }
springboot_validation_starter = { module = "org.springframework.boot:spring-boot-starter-validation" }
springboot_web_starter = { module = "org.springframework.boot:spring-boot-starter-web" }
springdoc_openapi_starter = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }

## Observability

honeycomb_opentelemetry_sdk = { module = "io.honeycomb:honeycomb-opentelemetry-sdk", version.ref = "honeycomb" }
honeycomb_opentelemetry_javaagent = { module = "io.honeycomb:honeycomb-opentelemetry-javaagent", version.ref = "honeycomb" }

# Persistence
flyway_core = { module = "org.flywaydb:flyway-core" }
hikaricp_core = { module = "com.zaxxer:HikariCP" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgres" }

# Testing
mockk_core = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk_spring = { module = "com.ninja-squad:springmockk", version.ref = "mockkSpring" }
testcontainers_jupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
testcontainers_postgres = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }

[bundles]

kotlin_all = [
    "kotlin_core",
    "kotlin_jackson_module",
    "kotlin_reflection",
    "kotlinx_coroutines_core",
    "kotlinx_coroutines_reactor",
    "kotlinx_coroutines_test",
]

springboot_all = [
    "springboot_actuator_starter",
    "springboot_jdbc_starter",
    "springboot_jooq_starter",
    "springboot_test_starter",
    "springboot_validation_starter",
    "springboot_web_starter",
]

persistence_support_all = [
    "flyway_core",
    "hikaricp_core",
]
